//
// Created by zhf on 2026/3/30.
//

#ifndef PATH_VALIDATION_MODULE_ROUTER_TYPES_H
#define PATH_VALIDATION_MODULE_ROUTER_TYPES_H
#define ROUTER_TYPE_NORMAL 1
#define ROUTER_TYPE_PATH_VALIDATION 2
#endif //PATH_VALIDATION_MODULE_ROUTER_TYPES_H
