//
// Created by zhf on 2026/4/21.
//

#ifndef PATH_VALIDATION_MODULE_SEC_PATH_MAB_TYPES_H
#define PATH_VALIDATION_MODULE_SEC_PATH_MAB_TYPES_H
#define SEC_PATH_MAB_TYPE_FIXED_BATCH 0
#define SEC_PATH_MAB_TYPE_DYNAMIC_BATCH 1
#endif //PATH_VALIDATION_MODULE_SEC_PATH_MAB_TYPES_H
