//
// Created by zhf on 2025/12/2.
//

#ifndef PATH_VALIDATION_MODULE_EPIC_FIELDS_LENGTH_H
#define PATH_VALIDATION_MODULE_EPIC_FIELDS_LENGTH_H


#define PATH_TIMESTAMP_LENGTH 8
#define HOP_IDENTIFIER_LENGTH 6
#define HOP_AUTHENTICATOR_LENGTH 16
#define HOP_VALIDATION_FIELD_LENGTH 3
#define SEGMENT_IDENTIFIER_LENGTH 2
#define PACKET_TIMESTAMP_LENGTH 8
#define ADDRESS_LENGTH 8
#define PATH_METADATA_LENGTH 12
#define DESTINATION_VALIDATION_LENGTH 16

#endif //PATH_VALIDATION_MODULE_EPIC_FIELDS_LENGTH_H
